# Generated by Django 5.0.7 on 2024-07-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Tital',
            new_name='title',
        ),
    ]
