# Generated by Django 5.0.6 on 2024-07-27 09:22

import django.db.models.deletion
import master.utils.TA_UNIQUE.filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to=master.utils.TA_UNIQUE.filename.unique_filename)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'Femail'), ('O', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
