# Generated by Django 5.0.6 on 2024-07-27 09:23

import master.utils.TA_UNIQUE.filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='img',
            field=models.ImageField(blank=True, upload_to=master.utils.TA_UNIQUE.filename.unique_filename),
        ),
    ]
