# Generated by Django 5.0.6 on 2024-07-27 12:28

import django.db.models.deletion
import master.utils.TA_UNIQUE.filename
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaymentEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('proof', models.ImageField(upload_to=master.utils.TA_UNIQUE.filename.unique_filename)),
                ('paid_date', models.DateField()),
                ('installment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
