# Generated by Django 5.0.6 on 2024-06-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
