# Generated by Django 5.0.6 on 2024-07-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society_member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='society_member',
            name='otp',
        ),
    ]
