# Generated by Django 5.0.6 on 2024-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_society_member_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society_member',
            name='house_number',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
