# Generated by Django 5.0.6 on 2024-07-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_society_member_house_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyWatchmen',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Watchmen_id', models.CharField(blank=True, max_length=225, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('number', models.CharField(max_length=225, unique=True)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
