# Generated by Django 5.0.6 on 2024-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
