# Generated by Django 5.0.6 on 2024-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_visitor_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='number',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
