# Generated by Django 5.0.6 on 2024-07-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_visitor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='entry_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='exit_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(),
        ),
    ]
