# Generated by Django 5.0.6 on 2024-07-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_visitor_entry_time_alter_visitor_exit_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='last_name',
        ),
    ]
