# Generated by Django 5.0.6 on 2024-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_visitor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='entry_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='exit_time',
            field=models.TimeField(blank=True),
        ),
    ]
