# Generated by Django 5.0.6 on 2024-07-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_visitor_exit_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='first_name',
            new_name='name',
        ),
    ]
