# Generated by Django 5.0.6 on 2024-07-09 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_first_name_visitor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='charman',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charman_id', models.CharField(blank=True, max_length=225, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
