# Generated by Django 5.0.6 on 2024-07-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_charman'),
    ]

    operations = [
        migrations.AddField(
            model_name='charman',
            name='email',
            field=models.EmailField(default='', max_length=225, unique=True),
            preserve_default=False,
        ),
    ]
