# Generated by Django 5.0.6 on 2024-07-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singupdata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='singupdata',
            name='otp',
        ),
    ]
