# Generated by Django 5.0.6 on 2024-07-21 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_remove_singupdata_is_active_remove_singupdata_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='role',
        ),
        migrations.AddField(
            model_name='singupdata',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mobile.role'),
            preserve_default=False,
        ),
    ]
