# Generated by Django 5.0.6 on 2024-07-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_role_singupdata'),
        ('mobile', '0005_rename_name_role_role_singupdata_role'),
    ]

    operations = [
    ]
