# Generated by Django 5.0.6 on 2024-07-27 09:58

import django.db.models.deletion
import master.utils.TA_UNIQUE.filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_assignbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_image', models.ImageField(upload_to=master.utils.TA_UNIQUE.filename.unique_filename)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'male'), ('F', 'Femail'), ('O', 'Other')], max_length=20, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
