# Generated by Django 5.0.6 on 2024-07-27 10:00

import master.utils.TA_UNIQUE.filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeeprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=master.utils.TA_UNIQUE.filename.unique_filename),
        ),
    ]
